# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScaphoidUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.FolderButton.setGeometry(QtCore.QRect(70, 20, 161, 51))
        self.FolderButton.setObjectName("FolderButton")
        self.ScapButton = QtWidgets.QPushButton(self.centralwidget)
        self.ScapButton.setGeometry(QtCore.QRect(330, 20, 161, 51))
        self.ScapButton.setObjectName("ScapButton")
        self.FracButton = QtWidgets.QPushButton(self.centralwidget)
        self.FracButton.setGeometry(QtCore.QRect(580, 20, 161, 51))
        self.FracButton.setObjectName("FracButton")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(790, 20, 291, 171))
        self.listView.setObjectName("listView")
        self.SourceImg = QtWidgets.QLabel(self.centralwidget)
        self.SourceImg.setGeometry(QtCore.QRect(70, 90, 311, 411))
        self.SourceImg.setText("")
        self.SourceImg.setScaledContents(False)
        self.SourceImg.setObjectName("SourceImg")
        self.ProcessImg = QtWidgets.QLabel(self.centralwidget)
        self.ProcessImg.setGeometry(QtCore.QRect(429, 90, 311, 411))
        self.ProcessImg.setText("")
        self.ProcessImg.setScaledContents(False)
        self.ProcessImg.setObjectName("ProcessImg")
        self.PredictImg = QtWidgets.QLabel(self.centralwidget)
        self.PredictImg.setGeometry(QtCore.QRect(110, 500, 221, 161))
        self.PredictImg.setText("")
        self.PredictImg.setScaledContents(False)
        self.PredictImg.setObjectName("PredictImg")
        self.FractureImg = QtWidgets.QLabel(self.centralwidget)
        self.FractureImg.setGeometry(QtCore.QRect(480, 500, 221, 161))
        self.FractureImg.setText("")
        self.FractureImg.setScaledContents(False)
        self.FractureImg.setObjectName("FractureImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FolderButton.setText(_translate("MainWindow", "Select Image Folder"))
        self.ScapButton.setText(_translate("MainWindow", "Detect Scaphoid"))
        self.FracButton.setText(_translate("MainWindow", "Classify & Detect Fracture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
